pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
                sh 'docker --version'
            }
        }

        stage('Build') {
            steps {
                dir('RIDEHUB USER AUTHENTICATION') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('RIDEHUB USER AUTHENTICATION') {
                    withCredentials([
                        string(
                            credentialsId: 'ridehub-db-url',
                            variable: 'DB_URL'
                        ),
                        usernamePassword(
                            credentialsId: 'ridehub-db',
                            usernameVariable: 'DB_USERNAME',
                            passwordVariable: 'DB_PASSWORD'
                        )
                    ]) {
                        sh 'mvn clean test'
                    }
                }
            }
        }

    }

    post {
        success {
            echo 'Build completed successfully!'
        }

        failure {
            echo 'Build failed. Check the Jenkins console output.'
        }
    }
}